Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2020-07, with the labels that each got.

#837 Add markdown sanity check CI
  .github/workflows/docfx.yml
  build/docfx.cmd
  docs/docfx.json
  docs/toc.yml
  src/OpenTelemetry.Exporter.Jaeger/README.md
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md
Labels: documentation, infra

#841 Add misspell to CI
  .github/workflows/spellcheck.yml
  samples/Exporters/Console/TestPrometheus.cs
  src/OpenTelemetry.Api/Context/Propagation/ITextFormat.cs
  src/OpenTelemetry.Api/Context/Propagation/ITextFormatActivity.cs
  src/OpenTelemetry.Api/Trace/Status.cs
  src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs
  src/OpenTelemetry/Metrics/CounterMetricSdkBase.cs
  src/OpenTelemetry/Metrics/MeterSdk.cs
  test/OpenTelemetry.Exporter.Prometheus.Tests/PrometheusExporterTests.cs
  test/OpenTelemetry.Instrumentation.Dependencies.Tests/HttpWebRequestActivitySourceTests.netfx.cs
  test/OpenTelemetry.Tests/Implementation/Trace/SpanTest.cs
Labels: documentation, infra

#741 Added options to HttpWebRequest instrumentation.
  src/OpenTelemetry.Api/Context/Propagation/ITextFormatActivity.cs
  src/OpenTelemetry.Api/Context/Propagation/TraceContextFormatActivity.cs
  src/OpenTelemetry.Api/Internal/OpenTelemetryApiEventSource.cs
  src/OpenTelemetry.Instrumentation.Dependencies/HttpClientInstrumentation.cs
  src/OpenTelemetry.Instrumentation.Dependencies/HttpClientInstrumentationOptions.cs
  src/OpenTelemetry.Instrumentation.Dependencies/HttpWebRequestInstrumentationOptions.netfx.cs
  src/OpenTelemetry.Instrumentation.Dependencies/Implementation/HttpHandlerDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.Dependencies/Implementation/HttpWebRequestActivitySource.netfx.cs
  src/OpenTelemetry.Instrumentation.Dependencies/OpenTelemetryBuilderExtensions.cs
  src/OpenTelemetry/Context/Propagation/B3Format.cs
  test/OpenTelemetry.Instrumentation.Dependencies.Tests/HttpClientTests.Basic.netcore31.cs
  test/OpenTelemetry.Instrumentation.Dependencies.Tests/HttpWebRequestActivitySourceTests.netfx.cs
  test/OpenTelemetry.Instrumentation.Dependencies.Tests/HttpWebRequestTests.Basic.netfx.cs
  test/OpenTelemetry.Instrumentation.Dependencies.Tests/HttpWebRequestTests.netfx.cs
Labels: area:sdk:instrumentation

#847 Basic docs
  README.md
  docs/instrumentation.md
  docs/sdk-usage.md
  samples/Exporters/Console/TestConsoleExporter.cs
  src/OpenTelemetry.Api/README.md
Labels: documentation

#851 Clean up doc structure
  .github/workflows/markdownlint.yml
  src/OpenTelemetry.Api/README.md
  src/OpenTelemetry.Exporter.Console/README.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md
  src/OpenTelemetry.Exporter.Prometheus/README.md
  src/OpenTelemetry.Exporter.ZPages/README.md
  src/OpenTelemetry.Exporter.Zipkin/README.md
  src/OpenTelemetry.Extensions.Hosting/README.md
  src/OpenTelemetry.Instrumentation.AspNetCore/README.md
  src/OpenTelemetry.Instrumentation.Dependencies/README.md
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md
  src/OpenTelemetry.Shims.OpenTracing/README.md
  src/OpenTelemetry/README.md
Labels: documentation

#856 Minor doc cleanup
  README.md
  src/OpenTelemetry.Instrumentation.AspNet.Win/README.md
  src/OpenTelemetry.Instrumentation.AspNetCore/README.md
Labels: documentation

#858 Move SDK doc, minor clean up
  README.md
  docs/sdk-usage.md
  samples/Exporters/Console/TestPrometheusExporter.cs
  src/OpenTelemetry.Api/README.md
  src/OpenTelemetry/README.md
Labels: documentation

#926 Trigger pipeline when tag
  .vsts/ci-myget-update.yml
  build/Common.prod.props
Labels: infra

#927 Add sanity check for non-ASCII character and trailing spaces
  .github/workflows/sanitycheck.yml
  build/sanitycheck.py
  examples/AspNet/Properties/AssemblyInfo.cs
  src/OpenTelemetry.Exporter.Jaeger/ApacheThrift/README.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/README.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md
  test/Benchmarks/README.md
  test/OpenTelemetry.Instrumentation.AspNetCore.Tests/OpenTelemetry.Instrumentation.AspNetCore.Tests.csproj
Labels: infra

#932 Minor: add link to the contribution graph
  README.md
Labels: documentation

#930 Updating ADO pipeline
  .vsts/ci-myget-update.yml
Labels: infra
