Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2020-08, with the labels that each got.

#966 Improve project props management
  Directory.Build.props
  Directory.Build.targets
  OpenTelemetry.sln
  build/Common.prod.props
  build/Common.props
  build/Common.test.props
  build/sanitycheck.py
  examples/AspNet/Web.Debug.config
  examples/AspNet/Web.Release.config
  src/Directory.Build.props
  src/Directory.Build.targets
  src/OpenTelemetry.Api/OpenTelemetry.Api.csproj
  src/OpenTelemetry/OpenTelemetry.csproj
  test/Directory.Build.props
  test/Directory.Build.targets
  test/OpenTelemetry.Instrumentation.SqlClient.Tests/dockerfile
  test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/dockerfile
Labels: infra

#990 Treat warning as warning for debug build
  build/Common.props
Labels: infra

#993 Use absolute path for project includes
  examples/AspNet/Examples.AspNet.csproj
  examples/AspNetCore/Examples.AspNetCore.csproj
  examples/Console/Examples.Console.csproj
  src/OpenTelemetry.Exporter.Console/OpenTelemetry.Exporter.Console.csproj
  src/OpenTelemetry.Exporter.Jaeger/OpenTelemetry.Exporter.Jaeger.csproj
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj
  src/OpenTelemetry.Exporter.Prometheus/OpenTelemetry.Exporter.Prometheus.csproj
  src/OpenTelemetry.Exporter.ZPages/OpenTelemetry.Exporter.ZPages.csproj
  src/OpenTelemetry.Exporter.Zipkin/OpenTelemetry.Exporter.Zipkin.csproj
  src/OpenTelemetry.Extensions.Hosting/OpenTelemetry.Extensions.Hosting.csproj
  src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
  src/OpenTelemetry.Instrumentation.AspNetCore/OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/OpenTelemetry.Instrumentation.Grpc/OpenTelemetry.Instrumentation.Grpc.csproj
  src/OpenTelemetry.Instrumentation.Http/OpenTelemetry.Instrumentation.Http.csproj
  src/OpenTelemetry.Instrumentation.SqlClient/OpenTelemetry.Instrumentation.SqlClient.csproj
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
  src/OpenTelemetry.Shims.OpenTracing/OpenTelemetry.Shims.OpenTracing.csproj
  src/OpenTelemetry/OpenTelemetry.csproj
  test/Benchmarks/Benchmarks.csproj
  test/OpenTelemetry.Exporter.Jaeger.Tests/OpenTelemetry.Exporter.Jaeger.Tests.csproj
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.csproj
  test/OpenTelemetry.Exporter.Prometheus.Tests/OpenTelemetry.Exporter.Prometheus.Tests.csproj
  test/OpenTelemetry.Exporter.ZPages.Tests/OpenTelemetry.Exporter.ZPages.Tests.csproj
  test/OpenTelemetry.Exporter.Zipkin.Tests/OpenTelemetry.Exporter.Zipkin.Tests.csproj
  test/OpenTelemetry.Extensions.Hosting.Tests/OpenTelemetry.Extensions.Hosting.Tests.csproj
  test/OpenTelemetry.Instrumentation.AspNet.Tests/OpenTelemetry.Instrumentation.AspNet.Tests.csproj
  test/OpenTelemetry.Instrumentation.AspNetCore.Tests/OpenTelemetry.Instrumentation.AspNetCore.Tests.csproj
  test/OpenTelemetry.Instrumentation.GrpcClient.Tests/OpenTelemetry.Instrumentation.GrpcClient.Tests.csproj
  test/OpenTelemetry.Instrumentation.Http.Tests/OpenTelemetry.Instrumentation.Http.Tests.csproj
  test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
  test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests.csproj
  test/OpenTelemetry.Shims.OpenTracing.Tests/OpenTelemetry.Shims.OpenTracing.Tests.csproj
  test/OpenTelemetry.Tests/OpenTelemetry.Tests.csproj
  test/TestApp.AspNetCore.2.1/TestApp.AspNetCore.2.1.csproj
  test/TestApp.AspNetCore.3.1/TestApp.AspNetCore.3.1.csproj
Labels: infra

#1002 Minor clean up
  README.md
  src/OpenTelemetry.Api/OpenTelemetry.Api.csproj
  src/OpenTelemetry.Shims.OpenTracing/OpenTelemetry.Shims.OpenTracing.csproj
  src/OpenTelemetry/OpenTelemetry.csproj
Labels: documentation, infra, pr:please-merge

#923 Creating CompositePropagator
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Api/Context/Propagation/CompositePropagator.cs
  src/OpenTelemetry.Api/Context/Propagation/ITextFormat.cs
  src/OpenTelemetry.Api/Context/Propagation/TraceContextFormat.cs
  src/OpenTelemetry.Api/Trace/SpanContext.cs
  src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs
  src/OpenTelemetry.Shims.OpenTracing/TracerShim.cs
  src/OpenTelemetry/Context/Propagation/B3Format.cs
  test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
  test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs
  test/OpenTelemetry.Shims.OpenTracing.Tests/TracerShimTests.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Propagation/B3FormatTest.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Propagation/CompositePropagatorTest.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Propagation/TestPropagator.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Propagation/TraceContextActivityTest.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Propagation/TraceContextTest.cs
Labels: area:api

#1001 Add custom sampler project
  OpenTelemetry.sln
  docs/trace/building-your-own-sampler/MySampler.cs
  docs/trace/building-your-own-sampler/Program.cs
  docs/trace/building-your-own-sampler/building-your-own-sampler.csproj
Labels: documentation, pr:please-merge

#997 Enable FxCop - part 01
  build/Common.props
  src/OpenTelemetry.Api/Context/CorrelationContext.cs
  src/OpenTelemetry.Api/Context/Propagation/TraceStateUtilsNew.cs
  src/OpenTelemetry.Api/Metrics/MeterProvider.cs
  src/OpenTelemetry.Api/Trace/TelemetrySpan.cs
  src/OpenTelemetry.Api/Trace/Tracer.cs
  src/OpenTelemetry.Api/Trace/TracerProvider.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporter.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/Batch.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerLog.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerSpan.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerSpanRef.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerTag.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerThriftClientTransport.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpBatcher.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpClient.cs
  src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs
  src/OpenTelemetry.Exporter.Jaeger/Process.cs
  src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs
  src/OpenTelemetry/Context/NoopDistributedContextBinarySerializer.cs
  src/OpenTelemetry/Context/Propagation/B3Format.cs
  src/OpenTelemetry/Context/Propagation/SerializationUtils.cs
  src/OpenTelemetry/Metrics/LabelSetSdk.cs
  src/OpenTelemetry/Metrics/MeterProviderSdk.cs
  src/OpenTelemetry/Trace/TracerProviderSdk.cs
Labels: pr:please-merge

#803 Add gRPC attributes for ASP.NET Core
  OpenTelemetry.sln
  src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/OpenTelemetry.Instrumentation.Grpc/AssemblyInfo.cs
  src/OpenTelemetry.Instrumentation.Grpc/GrpcTagHelper.cs
  src/OpenTelemetry.Instrumentation.Grpc/Implementation/GrpcClientDiagnosticListener.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/EventSourceTest.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcFixture.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTagHelperTests.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.client.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.server.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/OpenTelemetry.Instrumentation.Grpc.Tests.csproj
  test/OpenTelemetry.Instrumentation.Grpc.Tests/Proto/greet.proto
  test/OpenTelemetry.Instrumentation.Grpc.Tests/Services/GreeterService.cs
Labels: area:sdk:instrumentation

#1004 Add custom exporter project
  .github/codecov.yml
  OpenTelemetry.sln
  docs/trace/building-your-own-exporter/MyExporter.cs
  docs/trace/building-your-own-exporter/Program.cs
  docs/trace/building-your-own-exporter/TracerProviderBuilderExtensions.cs
  docs/trace/building-your-own-exporter/building-your-own-exporter.csproj
Labels: pr:please-merge

#996 Update the custom processor project
  docs/trace/building-your-own-processor/MyActivityProcessor.cs
  docs/trace/building-your-own-processor/Program.cs
Labels: documentation

#988 Make SuppressInstrumentation an IDisposable
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Sdk.cs
  src/OpenTelemetry/SuppressInstrumentationScope.cs
  test/OpenTelemetry.Tests/SuppressInstrumentationTest.cs
Labels: area:sdk, pr:please-merge

#1010 Updating CodeCoverage and deterministic build
  .github/workflows/dotnet-core-cov.yml
  build/Common.props
  build/process-codecoverage.ps1
  src/Directory.Build.targets
  test/Directory.Build.targets
Labels: infra, pr:please-merge

#1012 Updating Exporters to understand the array of primitives
  src/OpenTelemetry.Exporter.Console/ConsoleExporter.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerActivityExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs
  test/OpenTelemetry.Exporter.Jaeger.Tests/Implementation/JaegerActivityConversionTest.cs
  test/OpenTelemetry.Exporter.Jaeger.Tests/Implementation/JaegerUdpBatcherTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterTest.cs
Labels: pr:please-merge

#1014 Fix console output format
  docs/trace/getting-started/Program.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporter.cs
Labels: area:exporter, pr:please-merge

#1020 Use DisplayName instead of OperationName in ZipkinExporter
  src/OpenTelemetry.Exporter.Zipkin/Implementation/ZipkinActivityConversionExtensions.cs
Labels: pr:please-merge

#1022 Add build you own processor doc to sln
  OpenTelemetry.sln
Labels: pr:please-merge

#1017 Fix double shutdown
  docs/Directory.Build.props
  docs/trace/building-your-own-exporter/Program.cs
  docs/trace/building-your-own-exporter/TracerProviderExtensions.cs
  docs/trace/building-your-own-sampler/Program.cs
  docs/trace/getting-started/Program.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporter.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs
  src/OpenTelemetry.Exporter.ZPages/ZPagesProcessor.cs
  src/OpenTelemetry.Instrumentation.Http/Implementation/HttpTagHelper.cs
  src/OpenTelemetry/Metrics/MeterProviderSdk.cs
  src/OpenTelemetry/Sdk.cs
  src/OpenTelemetry/Trace/ActivityProcessor.cs
  src/OpenTelemetry/Trace/CompositeActivityProcessor.cs
  src/OpenTelemetry/Trace/Internal/NoopActivityProcessor.cs
  src/OpenTelemetry/Trace/TracerProviderExtensions.cs
  src/OpenTelemetry/Trace/TracerProviderSdk.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Config/ActivityProcessorPipelineTests.cs
  test/OpenTelemetry.Tests/Implementation/Trace/TraceSdkTest.cs
Labels: pr:please-merge

#936 End-to-end example applications
  OpenTelemetry.sln
  examples/MicroserviceExample/.dockerignore
  examples/MicroserviceExample/README.md
  examples/MicroserviceExample/Utils/Messaging/MessageReceiver.cs
  examples/MicroserviceExample/Utils/Messaging/MessageSender.cs
  examples/MicroserviceExample/Utils/Messaging/RabbitMqHelper.cs
  examples/MicroserviceExample/Utils/Utils.csproj
  examples/MicroserviceExample/WebApi/Controllers/SendMessageController.cs
  examples/MicroserviceExample/WebApi/Dockerfile
  examples/MicroserviceExample/WebApi/Program.cs
  examples/MicroserviceExample/WebApi/Startup.cs
  examples/MicroserviceExample/WebApi/WebApi.csproj
  examples/MicroserviceExample/WebApi/appsettings.Development.json
  examples/MicroserviceExample/WebApi/appsettings.json
  examples/MicroserviceExample/WorkerService/Dockerfile
  examples/MicroserviceExample/WorkerService/Program.cs
  examples/MicroserviceExample/WorkerService/Worker.cs
  examples/MicroserviceExample/WorkerService/WorkerService.csproj
  examples/MicroserviceExample/WorkerService/appsettings.Development.json
  examples/MicroserviceExample/WorkerService/appsettings.json
  examples/MicroserviceExample/docker-compose.yml
Labels: pr:please-merge

#1036 Rename AddActivitySource to AddSource, use params
  docs/trace/building-your-own-exporter/Program.cs
  docs/trace/building-your-own-processor/Program.cs
  docs/trace/building-your-own-sampler/Program.cs
  docs/trace/getting-started/Program.cs
  examples/Console/TestConsoleExporter.cs
  examples/Console/TestHttpClient.cs
  examples/Console/TestJaegerExporter.cs
  examples/Console/TestOTelShimWithConsoleExporter.cs
  examples/Console/TestOpenTracingWithConsoleExporter.cs
  examples/Console/TestOtlpExporter.cs
  examples/Console/TestRedis.cs
  examples/Console/TestZPagesExporter.cs
  examples/Console/TestZipkinExporter.cs
  examples/MicroserviceExample/WebApi/Startup.cs
  examples/MicroserviceExample/WorkerService/Program.cs
  src/OpenTelemetry.Instrumentation.Http/TracerProviderBuilderExtensions.cs
  src/OpenTelemetry.Instrumentation.SqlClient/TracerProviderBuilderExtensions.cs
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs
  src/OpenTelemetry/Trace/TracerProviderBuilder.cs
  test/Benchmarks/OpenTelemetrySdkBenchmarks.cs
  test/Benchmarks/OpenTelemetrySdkBenchmarksActivity.cs
  test/OpenTelemetry.Exporter.Jaeger.Tests/JaegerExporterTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterTest.cs
  test/OpenTelemetry.Exporter.ZPages.Tests/ZPagesExporterTests.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/ZipkinExporterTests.cs
  test/OpenTelemetry.Tests/Implementation/Trace/ActivityExtensionsTest.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Export/BatchingActivityProcessorTests.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Export/SimpleActivityProcessorTest.cs
  test/OpenTelemetry.Tests/Implementation/Trace/OpenTelemetrySdkTest.cs
  test/OpenTelemetry.Tests/Implementation/Trace/TraceSdkTest.cs
  test/OpenTelemetry.Tests/Implementation/Trace/TracerTest.cs
Labels: pr:please-merge

#1038 Update changelog format
  src/OpenTelemetry.Api/CHANGELOG.md
Labels: documentation

#1041 Remove unused files
  src/OpenTelemetry/Trace/ActivityProcessorPipelineBuilder.cs
  test/OpenTelemetry.Tests/Implementation/Trace/Config/ActivityProcessorPipelineTests.cs
Labels: pr:please-merge

#1047 Update MyExporter example
  docs/trace/building-your-own-exporter/MyExporterHelperExtensions.cs
Labels: area:exporter

#1051 Update console exporter
  docs/trace/building-your-own-sampler/MySampler.cs
  docs/trace/building-your-own-sampler/Program.cs
  docs/trace/getting-started/Program.cs
  examples/AspNetCore/Startup.cs
  examples/Console/TestConsoleExporter.cs
  examples/Console/TestHttpClient.cs
  examples/Console/TestOTelShimWithConsoleExporter.cs
  examples/Console/TestOpenTracingWithConsoleExporter.cs
  src/OpenTelemetry.Exporter.Console/CHANGELOG.md
  src/OpenTelemetry.Exporter.Console/ConsoleExporter.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporterHelperExtensions.cs
Labels: area:exporter

#1061 Adjust/fix wording
  README.md
  docs/trace/getting-started/README.md
Labels: pr:please-merge

#1068 Clean up
  src/OpenTelemetry/Trace/CompositeActivityProcessor.cs
  src/OpenTelemetry/Trace/Internal/FanOutActivityProcessor.cs
  src/OpenTelemetry/Trace/Internal/NoopActivityProcessor.cs
  test/Benchmarks/OpenTelemetrySdkBenchmarksActivity.cs
  test/OpenTelemetry.Tests/Trace/CompositeActivityProcessorTests.cs
  test/OpenTelemetry.Tests/Trace/FanOutActivityProcessorTests.cs
Labels: pr:please-merge

#1069 Micro optimization for built-in samplers
  src/OpenTelemetry/Trace/TracerProviderSdk.cs
Labels: pr:please-merge

#1066 Rename UseExporter to AddExporter
  examples/AspNet/Global.asax.cs
  examples/AspNetCore/Startup.cs
  examples/Console/TestJaegerExporter.cs
  examples/Console/TestOtlpExporter.cs
  examples/Console/TestRedis.cs
  examples/Console/TestZPagesExporter.cs
  examples/Console/TestZipkinExporter.cs
  examples/MicroserviceExample/WebApi/Startup.cs
  examples/MicroserviceExample/WorkerService/Program.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.Jaeger/CHANGELOG.md
  src/OpenTelemetry.Exporter.Jaeger/JaegerExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.Prometheus/CHANGELOG.md
  src/OpenTelemetry.Exporter.ZPages/CHANGELOG.md
  src/OpenTelemetry.Exporter.ZPages/ZPagesExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.Zipkin/CHANGELOG.md
  src/OpenTelemetry.Exporter.Zipkin/ZipkinExporterHelperExtensions.cs
  src/OpenTelemetry.Extensions.Hosting/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.Grpc/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md
  src/OpenTelemetry.Shims.OpenTracing/CHANGELOG.md
  test/OpenTelemetry.Exporter.Jaeger.Tests/JaegerExporterTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterTest.cs
  test/OpenTelemetry.Exporter.ZPages.Tests/ZPagesExporterTests.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/ZipkinExporterTests.cs
Labels: pr:please-merge

#1067 Make suppress instrumentation APIs less prone to introducing bugs
  docs/trace/building-your-own-exporter/MyExporter.cs
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Sdk.cs
  src/OpenTelemetry/SuppressInstrumentationScope.cs
  test/OpenTelemetry.Tests/SuppressInstrumentationTest.cs
Labels: pr:please-merge

#1085 Refactor exporter - step 4
  src/OpenTelemetry/Internal/CircularBuffer.cs
Labels: pr:please-merge

#1103 Migrate ZipkinExporter to BatchExportActivityProcessor
  src/OpenTelemetry.Exporter.Zipkin/CHANGELOG.md
  src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs
  src/OpenTelemetry.Exporter.Zipkin/ZipkinExporterHelperExtensions.cs
  test/Benchmarks/Exporter/ZipkinExporterBenchmarks.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/ZipkinExporterTests.cs
Labels: pr:please-merge

#1074 Updating VSTest nuget
  build/Common.nonprod.props
  build/Common.props
  build/process-codecoverage.ps1
Labels: pr:please-merge

#1140 Clean up exporter and processor
  docs/trace/building-your-own-processor/MyActivityProcessor.cs
  src/OpenTelemetry/Trace/ActivityExporter.cs
  src/OpenTelemetry/Trace/ActivityProcessor.cs
  src/OpenTelemetry/Trace/BatchExportActivityProcessor.cs
  src/OpenTelemetry/Trace/CompositeActivityProcessor.cs
  src/OpenTelemetry/Trace/ReentrantExportActivityProcessor.cs
  test/OpenTelemetry.Exporter.Jaeger.Tests/JaegerExporterTests.cs
  test/OpenTelemetry.Exporter.Jaeger.Tests/OpenTelemetry.Exporter.Jaeger.Tests.csproj
  test/OpenTelemetry.Exporter.Jaeger.Tests/TestActivityProcessor.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.csproj
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterTest.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/TestActivityProcessor.cs
  test/OpenTelemetry.Exporter.ZPages.Tests/OpenTelemetry.Exporter.ZPages.Tests.csproj
  test/OpenTelemetry.Exporter.ZPages.Tests/TestActivityProcessor.cs
  test/OpenTelemetry.Exporter.ZPages.Tests/ZPagesExporterTests.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/OpenTelemetry.Exporter.Zipkin.Tests.csproj
  test/OpenTelemetry.Exporter.Zipkin.Tests/TestActivityProcessor.cs
  test/OpenTelemetry.Tests/Shared/TestActivityProcessor.cs
Labels: pr:please-merge

#1142 Cleanup dispose/shutdown flow
  docs/trace/building-your-own-processor/MyActivityProcessor.cs
  src/OpenTelemetry.Shims.OpenTracing/TracerShim.cs
  src/OpenTelemetry/Trace/ActivityExporter.cs
  src/OpenTelemetry/Trace/ActivityProcessor.cs
  src/OpenTelemetry/Trace/BaseExportActivityProcessor.cs
  src/OpenTelemetry/Trace/BatchExportActivityProcessor.cs
  src/OpenTelemetry/Trace/ReentrantExportActivityProcessor.cs
  src/OpenTelemetry/Trace/SimpleExportActivityProcessor.cs
  src/OpenTelemetry/Trace/TracerProviderSdk.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/ZipkinExporterTests.cs
  test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.client.cs
  test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.Basic.netcore31.cs
  test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.netcore31.cs
  test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
  test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs
  test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
  test/OpenTelemetry.Tests/Shared/TestActivityProcessor.cs
Labels: pr:please-merge

#1152 Shutdown improvement
  docs/trace/building-your-own-exporter/MyExporter.cs
  docs/trace/building-your-own-exporter/README.md
  src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs
  src/OpenTelemetry/Trace/ActivityExporter.cs
  src/OpenTelemetry/Trace/BatchExportActivityProcessor.cs
Labels: pr:please-merge

#1160 Removing AI reference
  src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentationOptions.cs
  test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.Basic.netcore31.cs
Labels: pr:please-merge

#1164 More sanity check / cops
  NuGet.config
  build/OpenTelemetry.prod.loose.ruleset
  build/sanitycheck.py
  examples/AspNet/Examples.AspNet.csproj
  examples/AspNet/Views/Home/Index.cshtml
  examples/AspNet/Web.Debug.config
  examples/AspNet/Web.Release.config
  src/OpenTelemetry.Api/OpenTelemetry.Api.csproj
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs
  test/OpenTelemetry.Instrumentation.AspNet.Tests/OpenTelemetry.Instrumentation.AspNet.Tests.csproj
  test/OpenTelemetry.Instrumentation.AspNetCore.Tests/OpenTelemetry.Instrumentation.AspNetCore.Tests.csproj
  test/OpenTelemetry.Instrumentation.Http.Tests/OpenTelemetry.Instrumentation.Http.Tests.csproj
  test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
  test/OpenTelemetry.Shims.OpenTracing.Tests/OpenTelemetry.Shims.OpenTracing.Tests.csproj
Labels: enhancement, infra

#1202 Introduce a reentrant-mutex-like logic for suppress_instrumentation
  src/OpenTelemetry/SuppressInstrumentationScope.cs
  src/OpenTelemetry/Trace/TracerProviderSdk.cs
Labels: pr:please-merge

#1211 Refactor docs/demo
  OpenTelemetry.sln
  docs/trace/building-your-own-exporter/README.md
  docs/trace/building-your-own-instrumentation-library.md
  docs/trace/building-your-own-processor/Program.cs
  docs/trace/building-your-own-processor/README.md
  docs/trace/building-your-own-processor/building-your-own-processor.csproj
  docs/trace/building-your-own-sampler/Program.cs
  docs/trace/building-your-own-sampler/README.md
  docs/trace/building-your-own-sampler/building-your-own-sampler.csproj
  docs/trace/extending-the-sdk/MyExporter.cs
  docs/trace/extending-the-sdk/MyExporterHelperExtensions.cs
  docs/trace/extending-the-sdk/MyProcessor.cs
  docs/trace/extending-the-sdk/MySampler.cs
  docs/trace/extending-the-sdk/Program.cs
  docs/trace/extending-the-sdk/README.md
  docs/trace/extending-the-sdk/extending-the-sdk.csproj
  src/OpenTelemetry/README.md
Labels: pr:please-merge
