Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2020-10, with the labels that each got.

#1322 Consolidate log and trace processor
  docs/logs/getting-started/MyProcessor.cs
  src/OpenTelemetry/BaseProcessor.cs
  src/OpenTelemetry/Logs/CompositeLogProcessor.cs
  src/OpenTelemetry/Logs/LogProcessor.cs
  src/OpenTelemetry/Logs/OpenTelemetryLogger.cs
  src/OpenTelemetry/Trace/ActivityProcessor.cs
  test/Benchmarks/Benchmarks.csproj
  test/Benchmarks/Tracing/LogBenchmarks.cs
Labels: pr:please-merge

#1326 Fix nits: remove duplicated public keys
  src/OpenTelemetry/AssemblyInfo.cs
Labels: pr:please-merge

#1329 Respect Sdk.SuppressInstrumentation flag on the logging path
  src/OpenTelemetry/Logs/OpenTelemetryLogger.cs
Labels: pr:please-merge

#1331 Minor: Rename Benchmark/Tracing to Benchmark/Trace
  test/Benchmarks/Trace/ActivityCreationScenarios.cs
  test/Benchmarks/Trace/ActivitySourceAdapterBenchmark.cs
  test/Benchmarks/Trace/OpenTelemetrySdkBenchmarks.cs
  test/Benchmarks/Trace/OpenTelemetrySdkBenchmarksActivity.cs
  test/Benchmarks/Trace/SpanCreationScenarios.cs
  test/Benchmarks/Trace/TraceBenchmarks.cs
  test/Benchmarks/Trace/TraceShimBenchmarks.cs
Labels: pr:please-merge

#1332 Get rid of OpenTelemetry.Exporter.Console namespace
  src/OpenTelemetry.Exporter.Console/ActivitySpanIdConverter.cs
  src/OpenTelemetry.Exporter.Console/ActivityTraceIdConverter.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporter.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.Console/ConsoleExporterOptions.cs
Labels: pr:please-merge

#1338 Disable flaky patch coverage check
  .github/codecov.yml
Labels: infra

#1335 Add an InMemoryExporter<T>
  src/OpenTelemetry.Exporter.InMemory/CHANGELOG.md
  src/OpenTelemetry.Exporter.InMemory/InMemoryExporter.cs
  src/OpenTelemetry.Exporter.InMemory/InMemoryExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.InMemory/InMemoryExporterOptions.cs
  src/OpenTelemetry.Exporter.InMemory/OpenTelemetry.Exporter.InMemory.csproj
  src/OpenTelemetry.Exporter.InMemory/README.md
  test/OpenTelemetry.Tests/OpenTelemetry.Tests.csproj
  test/OpenTelemetry.Tests/Shared/TestActivityExporter.cs
  test/OpenTelemetry.Tests/Trace/BatchExportActivityProcessorTest.cs
  test/OpenTelemetry.Tests/Trace/ReentrantExportActivityProcessorTest.cs
  test/OpenTelemetry.Tests/Trace/SimpleExportActivityProcessorTest.cs
Labels: pr:please-merge

#1313 Updating Status based on the new spec
  examples/Console/TestRedis.cs
  src/OpenTelemetry.Api/Trace/ActivityExtensions.cs
  src/OpenTelemetry.Api/Trace/SpanHelper.cs
  src/OpenTelemetry.Api/Trace/Status.cs
  src/OpenTelemetry.Api/Trace/StatusCode.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/GrpcTagHelper.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs
  src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
  src/OpenTelemetry.Shims.OpenTracing/SpanBuilderShim.cs
  src/OpenTelemetry.Shims.OpenTracing/SpanShim.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterTest.cs
  test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
  test/OpenTelemetry.Instrumentation.AspNetCore.Tests/IncomingRequestsCollectionsIsAccordingToTheSpecTests.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTagHelperTests.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.client.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.server.cs
  test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.netcore31.cs
  test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestTests.netfx.cs
  test/OpenTelemetry.Instrumentation.Http.Tests/http-out-test-cases.json
  test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
  test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs
  test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
  test/OpenTelemetry.Shims.OpenTracing.Tests/SpanBuilderShimTests.cs
  test/OpenTelemetry.Shims.OpenTracing.Tests/SpanShimTests.cs
  test/OpenTelemetry.Tests/Trace/ActivityExtensionsTest.cs
  test/OpenTelemetry.Tests/Trace/StatusTest.cs
Labels: pr:please-merge

#1351 Introduce net461 target for OpenTelemetry logging component
  docs/Directory.Build.props
  src/OpenTelemetry.Exporter.InMemory/InMemoryExporterLoggingExtensions.cs
  src/OpenTelemetry.Exporter.InMemory/OpenTelemetry.Exporter.InMemory.csproj
  src/OpenTelemetry/Logs/LogRecord.cs
  src/OpenTelemetry/Logs/OpenTelemetryLogger.cs
  src/OpenTelemetry/Logs/OpenTelemetryLoggerOptions.cs
  src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs
  src/OpenTelemetry/Logs/OpenTelemetryLoggingExtensions.cs
  src/OpenTelemetry/OpenTelemetry.csproj
Labels: pr:please-merge

#1350 Fixing null reference in propertyfetcher
  src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
  src/OpenTelemetry/Instrumentation/PropertyFetcher.cs
  test/OpenTelemetry.Tests/Instrumentation/PropertyFetcherTest.cs
Labels: priority:p1

#1362 Catch up the latest version of .NET RC
  build/Common.nonprod.props
  docs/Directory.Build.props
  docs/trace/getting-started/README.md
  src/OpenTelemetry.Api/README.md
Labels: pr:please-merge

#1411 Update OpenTelemetry.API README.md to add Initial Tags using AcitivtyTagsCollection
  src/OpenTelemetry.Api/README.md
Labels: documentation, pr:please-merge

#1413 add support for true in x-b3-sampled
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Api/Context/Propagation/B3Propagator.cs
  test/OpenTelemetry.Tests/Trace/Propagation/B3PropagatorTest.cs
Labels: pr:please-merge
