Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2020-09, with the labels that each got.

#1214 Add doc on how to correlate ILogger with trace
  OpenTelemetry.sln
  README.md
  build/Common.nonprod.props
  docs/logs/building-your-own-exporter.md
  docs/logs/correlation/Program.cs
  docs/logs/correlation/README.md
  docs/logs/correlation/correlation.csproj
  docs/logs/getting-started.md
  docs/logs/logging-correlation.md
  docs/trace/extending-the-sdk/README.md
  docs/trace/getting-started/README.md
  src/OpenTelemetry/README.md
Labels: documentation, pr:please-merge

#1220 Minor improvement on the "extending the sdk" doc
  docs/trace/extending-the-sdk/README.md
Labels: documentation

#1221 Added GetTagValue Activity Extension
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Api/OpenTelemetry.Api.csproj
  src/OpenTelemetry.Api/Trace/ActivityExtensions.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/GrpcTagHelper.cs
  src/OpenTelemetry/Internal/EnumerationHelper.cs
  test/Benchmarks/ActivityBenchmarks.cs
  test/OpenTelemetry.Tests/Trace/ActivityExtensionsTest.cs
Labels: pr:please-merge

#1153 Support multiple spans (activities) within the same Trace for StackExchangeRedis
  src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs
  test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
Labels: pr:please-merge

#1213 Grpc.Net.Client instrumentation documentation
  src/OpenTelemetry.Instrumentation.GrpcNetClient/README.md
Labels: documentation, pr:please-merge

#1230 Centralize package versions for example projects
  build/Common.nonprod.props
  examples/AspNetCore/Examples.AspNetCore.csproj
  examples/Console/Examples.Console.csproj
  examples/GrpcService/Examples.GrpcService.csproj
  examples/MicroserviceExample/Utils/Utils.csproj
  examples/MicroserviceExample/WebApi/WebApi.csproj
  examples/MicroserviceExample/WorkerService/WorkerService.csproj
Labels: pr:please-merge

#1124 Adding W3C trace context integration test
  .github/workflows/integration.yml
  OpenTelemetry.sln
  test/OpenTelemetry.Instrumentation.W3cTraceContext.Tests/Dockerfile
  test/OpenTelemetry.Instrumentation.W3cTraceContext.Tests/InProcessServer.cs
  test/OpenTelemetry.Instrumentation.W3cTraceContext.Tests/OpenTelemetry.Instrumentation.W3cTraceContext.Tests.csproj
  test/OpenTelemetry.Instrumentation.W3cTraceContext.Tests/W3CTraceContextTests.cs
  test/OpenTelemetry.Instrumentation.W3cTraceContext.Tests/docker-compose.yml
Labels: pr:please-merge

#1250 Enforce EOL=LF in CI
  build/sanitycheck.py
  docs/trace/extending-the-sdk/MyExporter.cs
  docs/trace/extending-the-sdk/MyProcessor.cs
  docs/trace/extending-the-sdk/MySampler.cs
  docs/trace/extending-the-sdk/Program.cs
  docs/trace/getting-started/Program.cs
  src/OpenTelemetry.Api/Context/AsyncLocalRuntimeContextSlot.cs
  src/OpenTelemetry.Api/Context/RemotingRuntimeContextSlot.cs
  src/OpenTelemetry.Api/Context/RuntimeContext.cs
  src/OpenTelemetry.Api/Context/RuntimeContextSlot.cs
  src/OpenTelemetry.Api/Context/ThreadLocalRuntimeContextSlot.cs
  src/OpenTelemetry.Api/Trace/SemanticConventions.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/Int128.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpBatcher.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs
  src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs
  src/OpenTelemetry/Trace/TracerProviderSdk.cs
Labels: pr:please-merge

#1253 Sanitize EOL=LF for *.csproj files
  build/sanitycheck.py
  docs/trace/extending-the-sdk/extending-the-sdk.csproj
  docs/trace/getting-started/getting-started.csproj
  src/OpenTelemetry.Exporter.Jaeger/OpenTelemetry.Exporter.Jaeger.csproj
  test/OpenTelemetry.Exporter.Jaeger.Tests/OpenTelemetry.Exporter.Jaeger.Tests.csproj
Labels: pr:please-merge

#1184 Add SuppressInstrumentation to Grpc client
  src/OpenTelemetry.Instrumentation.GrpcNetClient/GrpcClientInstrumentation.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/GrpcClientInstrumentationOptions.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/TracerProviderBuilderExtensions.cs
  src/OpenTelemetry/Instrumentation/DiagnosticSourceListener.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.client.cs
Labels: pr:please-merge

#1257 Sanitize EOL=LF for *.md files
  README.md
  build/sanitycheck.py
  src/OpenTelemetry.Exporter.Console/README.md
  src/OpenTelemetry.Exporter.Jaeger/README.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/README.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md
  src/OpenTelemetry.Exporter.Prometheus/README.md
  src/OpenTelemetry.Exporter.ZPages/README.md
  src/OpenTelemetry.Exporter.Zipkin/README.md
  src/OpenTelemetry.Extensions.Hosting/README.md
  src/OpenTelemetry.Instrumentation.AspNetCore/README.md
  src/OpenTelemetry.Shims.OpenTracing/README.md
  src/OpenTelemetry/README.md
Labels: documentation

#1254 Jaeger Exporter Performance
  src/OpenTelemetry.Exporter.Jaeger/CHANGELOG.md
  src/OpenTelemetry.Exporter.Jaeger/Implementation/Batch.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/EmitBatchArgs.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerActivityExtensions.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerExporterEventSource.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerThriftClient.cs
  src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpBatcher.cs
  src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs
  src/OpenTelemetry.Exporter.Jaeger/JaegerExporterOptions.cs
  src/OpenTelemetry/AssemblyInfo.cs
  src/OpenTelemetry/Internal/PooledList.cs
  test/Benchmarks/Exporter/JaegerExporterBenchmarks.cs
  test/OpenTelemetry.Exporter.Jaeger.Tests/Implementation/JaegerUdpBatcherTests.cs
  test/OpenTelemetry.Exporter.Jaeger.Tests/JaegerExporterTests.cs
Labels: pr:please-merge

#1238 PropertyFetcher API Improvements
  src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Instrumentation/PropertyFetcher.cs
  test/OpenTelemetry.Tests/Instrumentation/PropertyFetcherTest.cs
Labels: pr:please-merge

#1282 Update Processor.Shutdown to meet with the latest spec
  docs/trace/extending-the-sdk/MyProcessor.cs
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Trace/ActivityExporter.cs
  src/OpenTelemetry/Trace/ActivityProcessor.cs
  src/OpenTelemetry/Trace/BaseExportActivityProcessor.cs
  src/OpenTelemetry/Trace/BatchExportActivityProcessor.cs
  src/OpenTelemetry/Trace/CompositeActivityProcessor.cs
  test/OpenTelemetry.Tests/Shared/TestActivityProcessor.cs
Labels: pr:please-merge

#1285 Update Exporter.Shutdown to meet with the latest spec
  docs/trace/extending-the-sdk/MyExporter.cs
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Trace/ActivityExporter.cs
Labels: pr:please-merge

#1290 Correct Resource URL in comment
  src/OpenTelemetry/Resources/Resource.cs
Labels: pr:please-merge

#1308 ILogger integration - part 1
  OpenTelemetry.sln
  build/Common.props
  docs/Directory.Build.props
  docs/logs/getting-started/Program.cs
  docs/logs/getting-started/README.md
  docs/logs/getting-started/getting-started.csproj
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry/Logs/OpenTelemetryLogger.cs
  src/OpenTelemetry/Logs/OpenTelemetryLoggerOptions.cs
  src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs
  src/OpenTelemetry/Logs/OpenTelemetryLoggingExtensions.cs
  src/OpenTelemetry/OpenTelemetry.csproj
Labels: pr:please-merge

#1309 Add more good/bad examples for ILogger
  docs/logs/getting-started/LoggerExtensions.cs
  docs/logs/getting-started/Program.cs
Labels: pr:please-merge

#1312 Remove Liudmila (Microsoft) from approvers list
  README.md
Labels: pr:please-merge
