Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2024-06, with the labels that each got.

#5664 [repo] Post-release automation improvements
  .github/workflows/post-release.yml
  build/RELEASING.md
  build/scripts/post-release.psm1
Labels: infra

#5673 Fix link to OTel calendar in readme
  README.md
Labels: documentation

#5648 Move LoggerProvider and friends (OTEL1000) to a stable API
  build/Common.nonprod.props
  build/Common.prod.props
  docs/diagnostics/experimental-apis/OTEL1000.md
  docs/diagnostics/experimental-apis/OTEL1001.md
  docs/logs/dedicated-pipeline/DedicatedLogging/DedicatedLoggingServiceCollectionExtensions.cs
  docs/logs/dedicated-pipeline/Program.cs
  docs/logs/getting-started-aspnetcore/Program.cs
  examples/AspNetCore/Program.cs
  src/OpenTelemetry.Api.ProviderBuilderExtensions/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Api.ProviderBuilderExtensions/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Api.ProviderBuilderExtensions/CHANGELOG.md
  src/OpenTelemetry.Api.ProviderBuilderExtensions/Logs/OpenTelemetryDependencyInjectionLoggerProviderBuilderExtensions.cs
  src/OpenTelemetry.Api.ProviderBuilderExtensions/Logs/OpenTelemetryDependencyInjectionLoggingServiceCollectionExtensions.cs
  src/OpenTelemetry.Api/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Api/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Api/Logs/IDeferredLoggerProviderBuilder.cs
  src/OpenTelemetry.Api/Logs/LoggerProvider.cs
  src/OpenTelemetry.Api/Logs/LoggerProviderBuilder.cs
  src/OpenTelemetry.Exporter.Console/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Exporter.Console/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Exporter.Console/CHANGELOG.md
  src/OpenTelemetry.Exporter.Console/ConsoleExporterLoggingExtensions.cs
  src/OpenTelemetry.Exporter.InMemory/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Exporter.InMemory/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Exporter.InMemory/CHANGELOG.md
  src/OpenTelemetry.Exporter.InMemory/InMemoryExporterLoggingExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpLogExporterHelperExtensions.cs
  src/OpenTelemetry.Extensions.Hosting/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Extensions.Hosting/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Extensions.Hosting/CHANGELOG.md
  src/OpenTelemetry.Extensions.Hosting/OpenTelemetryBuilder.cs
  src/OpenTelemetry/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry/BatchExportProcessor.cs
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Logs/Builder/LoggerProviderBuilderExtensions.cs
  src/OpenTelemetry/Logs/ILogger/OpenTelemetryLoggerOptions.cs
  src/OpenTelemetry/Logs/ILogger/OpenTelemetryLoggingExtensions.cs
  src/OpenTelemetry/Logs/LoggerProviderExtensions.cs
  src/OpenTelemetry/Logs/LoggerProviderSdk.cs
  src/OpenTelemetry/OpenTelemetryBuilderSdkExtensions.cs
  src/OpenTelemetry/Sdk.cs
  test/Benchmarks/Helper/LogRecordHelper.cs
  test/Benchmarks/Logs/LogBenchmarks.cs
  test/OpenTelemetry.Api.Tests/Logs/LoggerProviderTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/IntegrationTest/IntegrationTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpLogExporterTests.cs
  test/OpenTelemetry.Tests.Stress.Logs/Program.cs
Labels: pkg:OpenTelemetry.Api, pkg:OpenTelemetry, pkg:OpenTelemetry.Extensions.Hosting, pkg:OpenTelemetry.Api.ProviderBuilderExtensions

#5674 [repo] Add packages to releases when created by automation
  .github/workflows/publish-packages-1.0.yml
  build/scripts/post-release.psm1
Labels: infra

#5675 [repo] NuGet push release automation
  .github/workflows/post-release.yml
  .github/workflows/prepare-release.yml
  .github/workflows/publish-packages-1.0.yml
  build/RELEASING.md
  build/scripts/post-release.psm1
  build/scripts/prepare-release.psm1
Labels: infra

#5680 [repo] Fix a couple issues in automation workflows/scripts
  .github/workflows/automation.yml
  build/scripts/post-release.psm1
Labels: infra

#5681 [repo] Auto label pull requests
  .github/workflows/add-labels.yml
  .github/workflows/post-release.yml
  .github/workflows/prepare-release.yml
  OpenTelemetry.sln
  build/scripts/add-labels.ps1
  build/scripts/add-labels.psm1
  build/scripts/post-release.psm1
  build/scripts/prepare-release.psm1
Labels: infra

#5685 [repo] Replace Logging Exporter with Debug Exporter in otel-collector configs
  examples/AspNetCore/otel-collector.yaml
  examples/Console/otlp-collector-example/config.yaml
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/IntegrationTest/otel-collector-config.yaml
Labels: documentation

#5688 [repo] Bump tests and examples dependencies
  Directory.Packages.props
  test/OpenTelemetry.Tests/SuppressInstrumentationTest.cs
Labels: infra, dependencies

#5687 [api-baggage] revert space encoding change
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Api/Context/Propagation/BaggagePropagator.cs
  test/OpenTelemetry.Api.Tests/Trace/Propagation/BaggagePropagatorTest.cs
Labels: pkg:OpenTelemetry.Api

#5693 [repo] Auto-label PR workflow improvements
  build/scripts/add-labels.psm1
Labels: infra

#5696 [repo] Bump OTelLatestStableVer to 1.9.0 and fix coreunstable test issues
  Directory.Packages.props
  build/Common.prod.props
  build/Common.props
  test/OpenTelemetry.Exporter.Prometheus.AspNetCore.Tests/OpenTelemetry.Exporter.Prometheus.AspNetCore.Tests.csproj
  test/OpenTelemetry.Exporter.Prometheus.HttpListener.Tests/OpenTelemetry.Exporter.Prometheus.HttpListener.Tests.csproj
  test/OpenTelemetry.Shims.OpenTracing.Tests/OpenTelemetry.Shims.OpenTracing.Tests.csproj
Labels: pkg:OpenTelemetry.Exporter.Prometheus.AspNetCore, infra, dependencies, pkg:OpenTelemetry.Exporter.Prometheus.HttpListener, pkg:OpenTelemetry.Shims.OpenTracing

#5698 [repo] Stable version update automation tweaks
  .github/workflows/post-release.yml
  Directory.Packages.props
  build/scripts/post-release.psm1
Labels: infra, dependencies

#5700 [shared] Use CultureInfo.InvariantCulture in TagWriter
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md
  src/OpenTelemetry.Exporter.Zipkin/CHANGELOG.md
  src/Shared/TagWriter/TagWriter.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpTestHelpers.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/ZipkinExporterTests.cs
Labels: pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol, pkg:OpenTelemetry.Exporter.Zipkin

#5676 [prometheus] Fix collection output buffer management when its resized
  src/OpenTelemetry.Exporter.Prometheus.AspNetCore/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusCollectionManager.cs
  test/OpenTelemetry.Exporter.Prometheus.AspNetCore.Tests/PrometheusExporterMiddlewareTests.cs
  test/OpenTelemetry.Exporter.Prometheus.HttpListener.Tests/PrometheusHttpListenerTests.cs
Labels: pkg:OpenTelemetry.Exporter.Prometheus.AspNetCore, pkg:OpenTelemetry.Exporter.Prometheus.HttpListener

#5712 [repo] Simplify preprocessor directives
  src/OpenTelemetry.Api.ProviderBuilderExtensions/Logs/OpenTelemetryDependencyInjectionLoggerProviderBuilderExtensions.cs
  src/OpenTelemetry.Api.ProviderBuilderExtensions/Metrics/OpenTelemetryDependencyInjectionMeterProviderBuilderExtensions.cs
  src/OpenTelemetry.Api.ProviderBuilderExtensions/Trace/OpenTelemetryDependencyInjectionTracerProviderBuilderExtensions.cs
  src/OpenTelemetry.Api/Context/Propagation/TraceContextPropagator.cs
  src/OpenTelemetry.Api/Logs/LoggerProvider.cs
  src/OpenTelemetry.Api/Trace/Tracer.cs
  src/OpenTelemetry.Api/Trace/TracerProvider.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/BaseOtlpGrpcExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/BaseOtlpHttpExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpHttpLogExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpHttpMetricsExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpHttpTraceExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpRetry.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusCollectionManager.cs
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusSerializer.cs
  src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs
  src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs
  src/OpenTelemetry/Logs/Builder/LoggerProviderBuilderExtensions.cs
  src/OpenTelemetry/Logs/ILogger/OpenTelemetryLoggingExtensions.cs
  src/OpenTelemetry/Logs/LoggerProviderSdk.cs
  src/OpenTelemetry/Metrics/Builder/MeterProviderBuilderExtensions.cs
  src/OpenTelemetry/Metrics/MetricStreamIdentity.cs
  src/OpenTelemetry/Metrics/StringArrayEqualityComparer.cs
  src/OpenTelemetry/Metrics/Tags.cs
  src/OpenTelemetry/Trace/Builder/TracerProviderBuilderExtensions.cs
  src/OpenTelemetry/Trace/ExceptionProcessor.cs
  src/OpenTelemetry/Trace/SamplingResult.cs
  src/Shared/Guard.cs
  src/Shared/MathHelper.cs
  src/Shared/Metrics/Base2ExponentialBucketHistogramHelper.cs
  src/Shared/Options/DelegatingOptionsFactory.cs
  src/Shared/Options/DelegatingOptionsFactoryServiceCollectionExtensions.cs
  src/Shared/Options/SingletonOptionsManager.cs
  src/Shared/ThreadSafeRandom.cs
  test/OpenTelemetry.Api.Tests/Internal/GuardTest.cs
  test/OpenTelemetry.Api.Tests/Logs/LoggerProviderTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/Implementation/ExportClient/OtlpHttpTraceExportClientTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpRetryTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/TestHttpMessageHandler.cs
  test/OpenTelemetry.Extensions.Hosting.Tests/InMemoryExporterMetricsExtensionsTests.cs
  test/OpenTelemetry.Tests/Shared/MathHelper.cs
Labels: pkg:OpenTelemetry.Api, pkg:OpenTelemetry, pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol, pkg:OpenTelemetry.Extensions.Hosting, pkg:OpenTelemetry.Api.ProviderBuilderExtensions, pkg:OpenTelemetry.Exporter.Prometheus.HttpListener, pkg:OpenTelemetry.Exporter.Zipkin

#5706 [sdk] Organize related files into sub-folders
  docs/trace/extending-the-sdk/README.md
  src/OpenTelemetry/Logs/Processor/BatchExportLogRecordProcessorOptions.cs
  src/OpenTelemetry/Logs/Processor/BatchLogRecordExportProcessor.cs
  src/OpenTelemetry/Logs/Processor/LogRecordExportProcessorOptions.cs
  src/OpenTelemetry/Logs/Processor/SimpleLogRecordExportProcessor.cs
  src/OpenTelemetry/Metrics/MetricPoint/Base2ExponentialBucketHistogram.cs
  src/OpenTelemetry/Metrics/MetricPoint/ExponentialHistogramBuckets.cs
  src/OpenTelemetry/Metrics/MetricPoint/ExponentialHistogramData.cs
  src/OpenTelemetry/Metrics/MetricPoint/HistogramBucket.cs
  src/OpenTelemetry/Metrics/MetricPoint/HistogramBuckets.cs
  src/OpenTelemetry/Metrics/MetricPoint/MetricPoint.cs
  src/OpenTelemetry/Metrics/MetricPoint/MetricPointOptionalComponents.cs
  src/OpenTelemetry/Metrics/MetricPoint/MetricPointStatus.cs
  src/OpenTelemetry/Metrics/MetricPoint/MetricPointValueStorage.cs
  src/OpenTelemetry/Metrics/MetricPoint/MetricPointsAccessor.cs
  src/OpenTelemetry/Metrics/Reader/BaseExportingMetricReader.cs
  src/OpenTelemetry/Metrics/Reader/CompositeMetricReader.cs
  src/OpenTelemetry/Metrics/Reader/CompositeMetricReaderExt.cs
  src/OpenTelemetry/Metrics/Reader/MetricReader.cs
  src/OpenTelemetry/Metrics/Reader/MetricReaderExt.cs
  src/OpenTelemetry/Metrics/Reader/MetricReaderOptions.cs
  src/OpenTelemetry/Metrics/Reader/MetricReaderTemporalityPreference.cs
  src/OpenTelemetry/Metrics/Reader/PeriodicExportingMetricReader.cs
  src/OpenTelemetry/Metrics/Reader/PeriodicExportingMetricReaderOptions.cs
  src/OpenTelemetry/Metrics/View/Base2ExponentialBucketHistogramConfiguration.cs
  src/OpenTelemetry/Metrics/View/ExplicitBucketHistogramConfiguration.cs
  src/OpenTelemetry/Metrics/View/HistogramConfiguration.cs
  src/OpenTelemetry/Metrics/View/MetricStreamConfiguration.cs
  src/OpenTelemetry/Trace/Processor/ActivityExportProcessorOptions.cs
  src/OpenTelemetry/Trace/Processor/BatchActivityExportProcessor.cs
  src/OpenTelemetry/Trace/Processor/BatchExportActivityProcessorOptions.cs
  src/OpenTelemetry/Trace/Processor/ExceptionProcessor.cs
  src/OpenTelemetry/Trace/Processor/SimpleActivityExportProcessor.cs
  src/OpenTelemetry/Trace/Sampler/AlwaysOffSampler.cs
  src/OpenTelemetry/Trace/Sampler/AlwaysOnSampler.cs
  src/OpenTelemetry/Trace/Sampler/ParentBasedSampler.cs
  src/OpenTelemetry/Trace/Sampler/Sampler.cs
  src/OpenTelemetry/Trace/Sampler/SamplingDecision.cs
  src/OpenTelemetry/Trace/Sampler/SamplingParameters.cs
  src/OpenTelemetry/Trace/Sampler/SamplingResult.cs
  src/OpenTelemetry/Trace/Sampler/TraceIdRatioBasedSampler.cs
Labels: pkg:OpenTelemetry, documentation

#5714 [infra] Prepare release automation improvements
  .github/workflows/prepare-release.yml
  build/scripts/prepare-release.psm1
Labels: infra

#5708 [Exporter.OTLP] Mark as nullable
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/.publicApi/Stable/PublicAPI.Shipped.txt
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Builder/OpenTelemetryBuilderOtlpExporterExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Builder/OtlpExporterBuilder.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Builder/OtlpExporterBuilderOptions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Builder/UseOtlpExporterRegistration.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/IOtlpExporterOptions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExperimentalOptions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/BaseOtlpGrpcExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/ExportClientGrpcResponse.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/ExportClientHttpResponse.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/ExportClientResponse.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/IExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpGrpcLogExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpGrpcMetricsExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpGrpcTraceExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpHttpLogExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpHttpMetricsExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpHttpTraceExportClient.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/OtlpRetry.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/MetricItemExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpExporterOptionsConfigurationType.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpLogRecordTransformer.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpServiceCollectionExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpTagWriter.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ResourceExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/Transmission/OtlpExporterPersistentStorageTransmissionHandler.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/Transmission/OtlpExporterRetryTransmissionHandler.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/Transmission/OtlpExporterTransmissionHandler.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/Transmission/RetryHelper.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpLogExporter.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpLogExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpMetricExporter.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpMetricExporterExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpTraceExporter.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpTraceExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/PersistentStorage/DirectorySizeTracker.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/PersistentStorage/FileBlob.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/PersistentStorage/FileBlobProvider.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/PersistentStorage/PersistentBlob.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/PersistentStorage/PersistentBlobProvider.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/PersistentStorage/PersistentStorageHelper.cs
  src/Shared/Shims/NullableAttributes.cs
  src/Shared/TagWriter/TagWriter.cs
Labels: pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol

#5720 [Exporter.OTLP - Tests] Nullable
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/BaseOtlpHttpExportClientTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/Implementation/ExportClient/OtlpHttpTraceExportClientTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/IntegrationTest/IntegrationTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/MockCollectorIntegrationTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests.csproj
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpAttributeTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterOptionsExtensionsTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterOptionsTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpLogExporterTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpMetricsExporterTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpTestHelpers.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpTraceExporterTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/SdkLimitOptionsTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/TestExportClient.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/TestHttpMessageHandler.cs
  test/OpenTelemetry.Tests/Shared/EventSourceTestHelper.cs
  test/OpenTelemetry.Tests/Shared/SkipUnlessEnvVarFoundFactAttribute.cs
  test/OpenTelemetry.Tests/Shared/SkipUnlessEnvVarFoundTheoryAttribute.cs
  test/OpenTelemetry.Tests/Shared/TestActivityProcessor.cs
  test/OpenTelemetry.Tests/Shared/TestEventListener.cs
Labels: pkg:OpenTelemetry, pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol

#5710 [repo] Add Piotr as approver
  README.md
Labels: documentation

#5723 [infra] Version validation in prepare release workflow
  build/scripts/prepare-release.psm1
Labels: infra

#5728 [repo] Bump Microsoft.SourceLink.GitHub to 8.0.0
  Directory.Packages.props
Labels: infra, dependencies
