Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2024-01, with the labels that each got.

#5203 Update aspnetcore docs to remove prerelease
  docs/metrics/getting-started-aspnetcore/README.md
  docs/trace/getting-started-aspnetcore/README.md
Labels: documentation

#5023 [repo] CI improvements
  .github/codecov.yml
  .github/workflows/Component.BuildTest.yml
  .github/workflows/ci-aot-md.yml
  .github/workflows/ci-concurrency-md.yml
  .github/workflows/ci-instrumentation-libraries-md.yml
  .github/workflows/ci-instrumentation-libraries.yml
  .github/workflows/ci-md.yml
  .github/workflows/ci.yml
  .github/workflows/code-coverage.yml
  .github/workflows/concurrency-tests.yml
  .github/workflows/docfx.yml
  .github/workflows/dotnet-format-md.yml
  .github/workflows/dotnet-format.yml
  .github/workflows/integration-md.yml
  .github/workflows/integration.yml
  .github/workflows/markdownlint.yml
  .github/workflows/package-validation.yml
  .github/workflows/publish-packages-1.0.yml
  .github/workflows/sanitycheck.yml
  .github/workflows/verifyaotcompat.yml
  OpenTelemetry.sln
  build/Common.nonprod.props
Labels: Stale

#5208 [api] Fix Baggage context leak issue
  src/OpenTelemetry.Api/.publicApi/Stable/PublicAPI.Shipped.txt
  src/OpenTelemetry.Api/Baggage.cs
  src/OpenTelemetry.Api/CHANGELOG.md
  test/OpenTelemetry.Api.Tests/BaggageTests.cs
Labels: area:api

#5251 [otlp] Fix doc for LogRecord.EventId attributes
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md
Labels: area:exporter:otlp

#5257 [repo] Fix docfx build + improve CI for md-only PRs
  .github/workflows/ci.yml
  OpenTelemetry.sln
  docs/docfx.json
Labels: infra

#5258 [otlp] Remove Experimental Flag and emit stable Exception attributes by default
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExperimentalOptions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpLogRecordTransformer.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpLogExporterTests.cs
Labels: area:exporter:otlp

#4872 Add base class for implementing retry strategies in otlp exporter
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OpenTelemetryProtocolExporterEventSource.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/Retry/OtlpExporterTransmissionHandler.cs
Labels: area:exporter:otlp

#5281 [repo] markdownlint ci changes
  .github/workflows/ci.yml
  .github/workflows/markdownlint.yml
Labels: infra

#5279 Improve metrics docs
  docs/logs/README.md
  docs/metrics/README.md
Labels: documentation

#5255 [logs] Fix pooling issues when wrapping batch export processor
  src/OpenTelemetry/Batch.cs
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Logs/BatchLogRecordExportProcessor.cs
  src/OpenTelemetry/Logs/LogRecord.cs
  src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs
  src/OpenTelemetry/Logs/Pool/LogRecordThreadStaticPool.cs
  test/OpenTelemetry.Tests/Logs/BatchLogRecordExportProcessorTests.cs
  test/OpenTelemetry.Tests/Logs/LogRecordSharedPoolTests.cs
  test/OpenTelemetry.Tests/Logs/LogRecordThreadStaticPoolTests.cs
Labels: area:sdk, logs

#5278 [sdk] Perf improvement for TraceContextPropagator.Inject
  src/OpenTelemetry.Api/Context/Propagation/TraceContextPropagator.cs
Labels: area:sdk, traces

#5288 [repo-ci] Bump AurorNZ/paths-filter to resolve GitHub Node version warnings
  .github/workflows/ci.yml
Labels: infra

#5284 Improve metrics docs - part 2
  docs/metrics/README.md
  docs/metrics/getting-started-console/README.md
  docs/trace/getting-started-console/README.md
Labels: documentation, metrics
