Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2024-05, with the labels that each got.

#5584 [repo] Release process tweaks & improvements
  .github/workflows/publish-packages-1.0.yml
  OpenTelemetry.sln
  build/RELEASING.md
  build/generate-combined-changelog.ps1
Labels: infra

#5587 [repo] Release process tweaks & improvements 2
  .github/workflows/publish-packages-1.0.yml
Labels: infra

#5585 [otlp] Switch to TagWriter for handling of tags/attributes
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/MetricItemExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpLogRecordTransformer.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpTagTransformer.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpTagWriter.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ResourceExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj
  src/Shared/TagWriter/TagWriter.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpAttributeTests.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpTestHelpers.cs
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpTraceExporterTests.cs
Labels: area:exporter:otlp

#5589 [repo] Release process tweaks & improvements 3
  .github/workflows/publish-packages-1.0.yml
  build/RELEASING.md
Labels: infra

#5593 [Instrumentation.GrpcNetClient] Move to contrib repository
  .github/workflows/ci.yml
  Directory.Packages.props
  OpenTelemetry.sln
  README.md
  build/Common.props
  build/RELEASING.md
  docs/trace/extending-the-sdk/README.md
  examples/Console/Examples.Console.csproj
  src/OpenTelemetry.Instrumentation.AspNetCore/GrpcTagHelper.cs
  src/OpenTelemetry.Instrumentation.AspNetCore/OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/OpenTelemetry.Instrumentation.AspNetCore/StatusCanonicalCode.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/.publicApi/PublicAPI.Shipped.txt
  src/OpenTelemetry.Instrumentation.GrpcNetClient/.publicApi/PublicAPI.Unshipped.txt
  src/OpenTelemetry.Instrumentation.GrpcNetClient/AssemblyInfo.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/CHANGELOG.md
  src/OpenTelemetry.Instrumentation.GrpcNetClient/GrpcClientInstrumentation.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/GrpcClientTraceInstrumentationOptions.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/HttpRequestMessageContextPropagation.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcInstrumentationEventSource.cs
  src/OpenTelemetry.Instrumentation.GrpcNetClient/OpenTelemetry.Instrumentation.GrpcNetClient.csproj
  src/OpenTelemetry.Instrumentation.GrpcNetClient/README.md
  src/OpenTelemetry.Instrumentation.GrpcNetClient/TracerProviderBuilderExtensions.cs
  test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
  test/OpenTelemetry.Instrumentation.Grpc.Tests/EventSourceTest.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcServer.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTagHelperTests.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTestHelpers/ClientTestHelpers.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTestHelpers/ResponseUtils.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTestHelpers/TestHttpMessageHandler.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTestHelpers/TrailingHeadersHelpers.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.client.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.server.cs
  test/OpenTelemetry.Instrumentation.Grpc.Tests/OpenTelemetry.Instrumentation.Grpc.Tests.csproj
  test/OpenTelemetry.Instrumentation.Grpc.Tests/Proto/greet.proto
  test/OpenTelemetry.Instrumentation.Grpc.Tests/Services/GreeterService.cs
Labels: area:instrumentation

#5594 [repo] Switching bug template to YAML
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: infra

#5527 [Otlp] Add disk retry enablement
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExperimentalOptions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpExporterOptionsExtensionsTests.cs
Labels: area:exporter:otlp

#5595 [repo] Change Markdown issue templates to YAML
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yaml
Labels: infra

#5601 [repo] Automatically add area labels when new issue is opened
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/add-labels.yml
  OpenTelemetry.sln
Labels: infra

#5558 [sdk-metrics] ExemplarReservoir dedicated diagnostic and custom ExemplarReservoir support
  OpenTelemetry.sln
  build/Common.props
  docs/diagnostics/experimental-apis/OTEL1002.md
  docs/diagnostics/experimental-apis/OTEL1004.md
  docs/diagnostics/experimental-apis/README.md
  src/OpenTelemetry/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Metrics/Exemplar/ExemplarMeasurement.cs
  src/OpenTelemetry/Metrics/Exemplar/ExemplarReservoir.cs
  src/OpenTelemetry/Metrics/Exemplar/FixedSizeExemplarReservoir.cs
  src/OpenTelemetry/Metrics/MetricPoint.cs
  src/OpenTelemetry/Metrics/MetricStreamConfiguration.cs
  src/Shared/DiagnosticDefinitions.cs
Labels: area:sdk, metrics

#5605 [repo] Add-labels workflow fix
  .github/workflows/add-labels.yml
  OpenTelemetry.sln
  build/scripts/add-labels.ps1
Labels: infra

#5609 [repo] Clean up nits (s/can not/cannot/) in bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: infra

#5608 [doc] update package level warning messages
  src/OpenTelemetry.Exporter.Console/README.md
  src/OpenTelemetry.Exporter.InMemory/README.md
  src/OpenTelemetry.Exporter.Prometheus.AspNetCore/README.md
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/README.md
Labels: documentation

#5598 [repo] Release process tweaks & improvements 4
  .github/workflows/prepare-release.yml
  .github/workflows/publish-packages-1.0.yml
  .markdownlint.yaml
  OpenTelemetry.sln
  build/RELEASING.md
  build/scripts/finalize-publicapi.ps1
  build/scripts/prepare-release.psm1
  build/scripts/update-changelogs.ps1
Labels: infra

#5607 [sdk-metrics] Expose Exemplars stable
  OpenTelemetry.sln
  docs/diagnostics/experimental-apis/OTEL1002.md
  docs/diagnostics/experimental-apis/README.md
  src/OpenTelemetry/.publicApi/Experimental/PublicAPI.Unshipped.txt
  src/OpenTelemetry/.publicApi/Stable/PublicAPI.Unshipped.txt
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Metrics/Builder/MeterProviderBuilderExtensions.cs
  src/OpenTelemetry/Metrics/Exemplar/Exemplar.cs
  src/OpenTelemetry/Metrics/Exemplar/ExemplarFilterType.cs
  src/OpenTelemetry/Metrics/Exemplar/ReadOnlyExemplarCollection.cs
  src/OpenTelemetry/Metrics/MeterProviderSdk.cs
  src/OpenTelemetry/Metrics/MetricPoint.cs
  src/OpenTelemetry/ReadOnlyFilteredTagCollection.cs
  src/Shared/DiagnosticDefinitions.cs
  test/OpenTelemetry.Tests/Metrics/MetricExemplarTests.cs
Labels: area:sdk, metrics

#5610 [repo] Add minimal reproducible example link to the issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: infra

#5612 [repo] Switch to component label for tagging issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  build/scripts/add-labels.ps1
Labels: infra

#5617 [repo] Post-release workflow refactor
  .github/workflows/publish-packages-1.0.yml
  OpenTelemetry.sln
  build/scripts/post-release.psm1
Labels: infra

#5619 [repo] Build script organization
  .github/workflows/concurrency-tests.yml
  .github/workflows/sanitycheck.yml
  .github/workflows/verifyaotcompat.yml
  OpenTelemetry.sln
  build/scripts/sanitycheck.py
  build/scripts/test-aot-compatibility.ps1
  build/scripts/test-threadSafety.ps1
Labels: infra

#5614 [sdk-traces] SamplingResult constructors accept null parameters
  src/OpenTelemetry/.publicApi/Stable/PublicAPI.Shipped.txt
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Trace/SamplingResult.cs
Labels: pkg:OpenTelemetry, traces

#5611 [sdk-metrics] Add experimental envvar for setting ExemplarFilter for histograms
  docs/metrics/customizing-the-sdk/README.md
  examples/AspNetCore/Program.cs
  src/OpenTelemetry/CHANGELOG.md
  src/OpenTelemetry/Metrics/MeterProviderSdk.cs
  src/OpenTelemetry/Metrics/Metric.cs
  src/OpenTelemetry/Metrics/MetricReaderExt.cs
  src/OpenTelemetry/Metrics/MetricStreamIdentity.cs
  test/OpenTelemetry.Tests/Metrics/MetricExemplarTests.cs
Labels: pkg:OpenTelemetry, metrics

#5623 [prometheus] Fix issue with corrupted buffers when reading both OpenMetrics and plain text formats
  src/OpenTelemetry.Exporter.Prometheus.AspNetCore/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.AspNetCore/PrometheusExporterMiddleware.cs
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusCollectionManager.cs
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/PrometheusHttpListener.cs
  test/OpenTelemetry.Exporter.Prometheus.AspNetCore.Tests/PrometheusExporterMiddlewareTests.cs
  test/OpenTelemetry.Exporter.Prometheus.HttpListener.Tests/PrometheusCollectionManagerTests.cs
Labels: pkg:OpenTelemetry.Exporter.Prometheus.AspNetCore, pkg:OpenTelemetry.Exporter.Prometheus.HttpListener

#5630 [sdk-metrics] Update Exemplars before MetricPoint CompleteUpdate fires
  src/OpenTelemetry/Metrics/MetricPoint.cs
Labels: pkg:OpenTelemetry, metrics

#5628 [OTLP] Add details for offline storage
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/README.md
Labels: pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol, documentation

#5624 [docs-metrics] Customer ExemplarReservoir and View API configuration
  docs/diagnostics/experimental-apis/OTEL1004.md
  docs/metrics/customizing-the-sdk/README.md
  docs/metrics/extending-the-sdk/README.md
Labels: documentation, metrics

#5636 [docs] Improve exemplars tutorial
  docs/metrics/exemplars/Program.cs
  docs/metrics/exemplars/README.md
  docs/metrics/exemplars/exemplars.csproj
Labels: documentation

#5644 [docs] Tweak ToC
  docs/metrics/getting-started-prometheus-grafana/README.md
  docs/trace/getting-started-jaeger/README.md
Labels: documentation

#5645 [repo] Fix variable usage in test-aot-compatibility script
  build/scripts/test-aot-compatibility.ps1
Labels: infra

#5640 [docs] Move docker related files to examples folder
  examples/AspNetCore/docker-compose.yaml
  examples/AspNetCore/grafana-datasources.yaml
  examples/AspNetCore/otel-collector.yaml
  examples/AspNetCore/prometheus.yaml
  examples/AspNetCore/tempo.yaml
Labels: documentation

#5651 [repo] CI tweaks and improvements
  .github/codecov.yml
  .github/workflows/Component.BuildTest.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dotnet-format.yml
  .github/workflows/package-validation.yml
  .github/workflows/publish-packages-1.0.yml
  OpenTelemetry.sln
  build/OpenTelemetry.proj
  build/UnstableCoreLibraries.proj
Labels: infra

#5646 [prometheus] Fix OpenMetrics format suffixes
  src/OpenTelemetry.Exporter.Prometheus.AspNetCore/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusMetric.cs
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusSerializer.cs
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusSerializerExt.cs
  test/OpenTelemetry.Exporter.Prometheus.AspNetCore.Tests/PrometheusExporterMiddlewareTests.cs
  test/OpenTelemetry.Exporter.Prometheus.HttpListener.Tests/PrometheusHttpListenerTests.cs
  test/OpenTelemetry.Exporter.Prometheus.HttpListener.Tests/PrometheusMetricTests.cs
Labels: pkg:OpenTelemetry.Exporter.Prometheus.AspNetCore, pkg:OpenTelemetry.Exporter.Prometheus.HttpListener

#5657 [repo] Release automation improvements
  .github/workflows/automation.yml
  .github/workflows/post-release.yml
  .github/workflows/prepare-release.yml
  .github/workflows/publish-packages-1.0.yml
  OpenTelemetry.sln
  build/scripts/post-release.psm1
  build/scripts/prepare-release.psm1
Labels: infra

#5659 [repo] Reduce explicit package references on newer TFM's
  src/Directory.Build.targets
  src/OpenTelemetry.Exporter.Console/OpenTelemetry.Exporter.Console.csproj
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj
  src/OpenTelemetry.Exporter.Zipkin/OpenTelemetry.Exporter.Zipkin.csproj
  test/Directory.Build.targets
Labels: pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol, pkg:OpenTelemetry.Exporter.Console, pkg:OpenTelemetry.Exporter.Zipkin
