Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2024-08, with the labels that each got.

#5769 [docs-metrics] Fix tuple vs KVP confusion in code sample
  docs/metrics/README.md
Labels: documentation

#5772 [repo] Add ReleaseNotes.md to include features shipped in stable release
  OpenTelemetry.sln
  RELEASENOTES.md
  build/RELEASING.md
  src/OpenTelemetry.Api.ProviderBuilderExtensions/CHANGELOG.md
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Exporter.Console/CHANGELOG.md
  src/OpenTelemetry.Exporter.InMemory/CHANGELOG.md
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.AspNetCore/CHANGELOG.md
  src/OpenTelemetry.Exporter.Prometheus.HttpListener/CHANGELOG.md
  src/OpenTelemetry.Exporter.Zipkin/CHANGELOG.md
  src/OpenTelemetry.Extensions.Hosting/CHANGELOG.md
  src/OpenTelemetry.Extensions.Propagators/CHANGELOG.md
  src/OpenTelemetry.Shims.OpenTracing/CHANGELOG.md
  src/OpenTelemetry/CHANGELOG.md
Labels: pkg:OpenTelemetry.Api, pkg:OpenTelemetry, pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol, pkg:OpenTelemetry.Exporter.Prometheus.AspNetCore, documentation, infra, pkg:OpenTelemetry.Extensions.Hosting, pkg:OpenTelemetry.Api.ProviderBuilderExtensions, pkg:OpenTelemetry.Exporter.Console, pkg:OpenTelemetry.Exporter.InMemory, pkg:OpenTelemetry.Exporter.Prometheus.HttpListener, pkg:OpenTelemetry.Exporter.Zipkin, pkg:OpenTelemetry.Extensions.Propagators, pkg:OpenTelemetry.Shims.OpenTracing

#5749 [api] Optimise `TraceContextPropagator.Extract`
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Api/Context/Propagation/TraceContextPropagator.cs
  test/Benchmarks/Context/Propagation/TraceContextPropagatorBenchmarks.cs
  test/OpenTelemetry.Tests/Trace/Propagation/TraceContextPropagatorTest.cs
Labels: pkg:OpenTelemetry.Api, pkg:OpenTelemetry, perf

#5780 [release] Add release notes link on stable releases
  build/scripts/post-release.psm1
Labels: infra

#5784 [repo] Enable NuGetAudit
  build/Common.props
Labels: infra

#5787 [repo] update stale automation to inspect issues
  .github/workflows/stale.yml
Labels: infra

#5789 [sdk] Switch a couple guard calls to debug.assert in CircularBuffer
  src/OpenTelemetry/Internal/CircularBuffer.cs
  test/OpenTelemetry.Tests/Internal/CircularBufferTest.cs
Labels: pkg:OpenTelemetry

#5788 [repo] Add needs-triage label to new issues created via templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/stale.yml
Labels: infra

#5790 Log Stress test to follow recommended logging practise
  test/OpenTelemetry.Tests.Stress.Logs/LoggerExtensions.cs
  test/OpenTelemetry.Tests.Stress.Logs/Program.cs
Labels: perf

#5796 [repo] Update stale.yml - reduce days before stale to 1000
  .github/workflows/stale.yml
Labels: infra

#5795 [repo] Remove .NET 7 target
  .github/workflows/Component.BuildTest.yml
  .github/workflows/ci.yml
  Directory.Packages.props
  OpenTelemetry.sln
  build/Common.props
  build/docker-compose.net7.0.yml
Labels: infra, dependencies

#5781 [api] Mark SetStatus & GetStatus ActivityExtensions obsolete
  src/OpenTelemetry.Api/.publicApi/Stable/PublicAPI.Shipped.txt
  src/OpenTelemetry.Api/CHANGELOG.md
  src/OpenTelemetry.Api/Trace/ActivityExtensions.cs
  src/OpenTelemetry.Api/Trace/TelemetrySpan.cs
  src/OpenTelemetry.Shims.OpenTracing/OpenTelemetry.Shims.OpenTracing.csproj
  src/OpenTelemetry/Trace/Processor/ExceptionProcessor.cs
  src/Shared/ActivityHelperExtensions.cs
  src/Shared/AssemblyVersionExtensions.cs
  test/Directory.Packages.props
  test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpTraceExporterTests.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/Implementation/ZipkinActivityConversionTest.cs
  test/OpenTelemetry.Exporter.Zipkin.Tests/ZipkinExporterTests.cs
  test/OpenTelemetry.Shims.OpenTracing.Tests/OpenTelemetry.Shims.OpenTracing.Tests.csproj
  test/OpenTelemetry.Shims.OpenTracing.Tests/SpanBuilderShimTests.cs
  test/OpenTelemetry.Shims.OpenTracing.Tests/SpanShimTests.cs
  test/OpenTelemetry.Shims.OpenTracing.Tests/VersionHelper.cs
Labels: pkg:OpenTelemetry.Api, pkg:OpenTelemetry, pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol, pkg:OpenTelemetry.Exporter.Zipkin, pkg:OpenTelemetry.Shims.OpenTracing

#5767 [Propagators] Nullable annotations
  src/OpenTelemetry.Api/.publicApi/Stable/PublicAPI.Shipped.txt
  src/OpenTelemetry.Api/Context/Propagation/B3Propagator.cs
  src/OpenTelemetry.Api/Context/Propagation/BaggagePropagator.cs
  src/OpenTelemetry.Api/Context/Propagation/CompositeTextMapPropagator.cs
  src/OpenTelemetry.Api/Context/Propagation/NoopTextMapPropagator.cs
  src/OpenTelemetry.Api/Context/Propagation/PropagationContext.cs
  src/OpenTelemetry.Api/Context/Propagation/Propagators.cs
  src/OpenTelemetry.Api/Context/Propagation/TextMapPropagator.cs
  src/OpenTelemetry.Api/Context/Propagation/TraceContextPropagator.cs
  src/OpenTelemetry.Api/Context/Propagation/TraceStateUtilsNew.cs
  src/OpenTelemetry.Api/Trace/SpanContext.cs
  src/OpenTelemetry.Extensions.Propagators/.publicApi/PublicAPI.Shipped.txt
  src/OpenTelemetry.Extensions.Propagators/B3Propagator.cs
  src/OpenTelemetry.Extensions.Propagators/JaegerPropagator.cs
  src/OpenTelemetry.Extensions.Propagators/OpenTelemetry.Extensions.Propagators.csproj
  test/OpenTelemetry.Api.Tests/Context/Propagation/B3PropagatorTest.cs
  test/OpenTelemetry.Api.Tests/Context/Propagation/BaggagePropagatorTest.cs
  test/OpenTelemetry.Api.Tests/Context/Propagation/CompositePropagatorTest.cs
  test/OpenTelemetry.Api.Tests/Context/Propagation/PropagatorsTest.cs
  test/OpenTelemetry.Api.Tests/Context/Propagation/TestPropagator.cs
  test/OpenTelemetry.Api.Tests/Context/Propagation/TracestateUtilsTests.cs
  test/OpenTelemetry.Extensions.Propagators.Tests/B3PropagatorTest.cs
  test/OpenTelemetry.Extensions.Propagators.Tests/JaegerPropagatorTest.cs
  test/OpenTelemetry.Extensions.Propagators.Tests/OpenTelemetry.Extensions.Propagators.Tests.csproj
Labels: pkg:OpenTelemetry.Api, pkg:OpenTelemetry.Extensions.Propagators

#5808 [otlp] Workaround DI containers which create unregistered services
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Builder/OtlpExporterBuilder.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Builder/UseOtlpExporterRegistration.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md
Labels: pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol

#5807 [benchmarks.logging] Use source generator pattern
  test/Benchmarks/Logs/Food.cs
  test/Benchmarks/Logs/LogBenchmarks.cs
  test/Benchmarks/Logs/LoggerExtensions.cs
Labels: perf

#5811 [docs] Fix OTLP Collector config in example app
  examples/Console/otlp-collector-example/config.yaml
Labels: documentation
