Repository open-telemetry/opentelemetry-dotnet, pull requests merged in 2025-07, with the labels that each got.

#6369 Remove redundant test
  test/OpenTelemetry.Tests/Trace/LinkTests.cs
Labels: pkg:OpenTelemetry

#6384 Slight improvement to readability to Metric ConsoleExporter
  src/OpenTelemetry.Exporter.Console/ConsoleMetricExporter.cs
Labels: pkg:OpenTelemetry.Exporter.Console

#6409 [infra] use env. var. to read github body comment
  .github/workflows/prepare-release.yml
Labels: infra, ready to merge

#6414 [docs] Contributing - reporting bug/feature requests
  .github/ISSUE_TEMPLATE/bug_report.yml
  CONTRIBUTING.md
Labels: documentation, infra

#6413 [Infra] Exclude keep-open label from stale
  .github/workflows/stale.yml
Labels: infra

#6398 [OTLP] Dispose exporter if setup fails
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpLogExporterHelperExtensions.cs
  src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpTraceExporterHelperExtensions.cs
Labels: pkg:OpenTelemetry.Exporter.OpenTelemetryProtocol

#6415 [Infra] Improve CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: infra
